DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER(
    ID VARCHAR2(200) PRIMARY KEY,
    PWD VARCHAR2(200) NOT NULL,
    NAME VARCHAR2(200) NOT NULL,
    NICK VARCHAR2(200) NOT NULL,
    PHONE VARCHAR2(200) NOT NULL,
    MAIL VARCHAR2(200) NOT NULL,
    AGE VARCHAR2(200) NOT NULL,
    HEIGHT VARCHAR2(200) NOT NULL,
    WEIGHT VARCHAR2(200) NOT NULL,
    POSITION VARCHAR2(200) NOT NULL,
    ATHLETE VARCHAR2(200) NOT NULL,
    LEVELS VARCHAR2(200) NOT NULL,
    POINT VARCHAR2(200) DEFAULT '0',
    ROLE VARCHAR2(200) DEFAULT 'MEMBER',
    STATUS VARCHAR2(200) DEFAULT 'Y'
);

DROP SEQUENCE SEQ_UNO;
CREATE SEQUENCE SEQ_UNO;

COMMENT ON COLUMN MEMBER.ID IS '회원아이디';
COMMENT ON COLUMN MEMBER.PASSWORD IS '회원비밀번호';
COMMENT ON COLUMN MEMBER.NAME IS '회원명';
COMMENT ON COLUMN MEMBER.NICK IS '닉네임';
COMMENT ON COLUMN MEMBER.PHONE IS '전화번호';
COMMENT ON COLUMN MEMBER.MAIL IS '이메일';
COMMENT ON COLUMN MEMBER.AGE IS '나이';
COMMENT ON COLUMN MEMBER.HEIGHT IS '키';
COMMENT ON COLUMN MEMBER.WEIGHT IS '몸무게';
COMMENT ON COLUMN MEMBER.POSITION IS '선호포지션';
COMMENT ON COLUMN MEMBER.ATHLETE IS '선수출신여부';
COMMENT ON COLUMN MEMBER.LEVELS IS '레벨';
COMMENT ON COLUMN MEMBER.POINT IS '포인트';
COMMENT ON COLUMN MEMBER.ROLE IS '권한';
COMMENT ON COLUMN MEMBER.STATUS IS '상태';


INSERT INTO MEMBER VALUES('admin', '1234', 'ADMIN', 'ADMIN', '010-1234-5678', 'ADMIN@ADMIN.COM', '0000/12/12',
    '180', '70', 'FW', '선출', '세미', DEFAULT, 'ADMIN', DEFAULT);

COMMIT;

SELECT * FROM MEMBER;
------------------------------------------------
--------------- Board 관련 테이블 ------------
------------------------------------------------


DROP TABLE BOARD CASCADE CONSTRAINTS;
CREATE TABLE BOARD (	
    NO NUMBER,
    WRITER_ID VARCHAR2(200), 
	TITLE VARCHAR2(50), 
	CONTENT VARCHAR2(2000), 
	TYPE VARCHAR2(100), 
	ORIGINAL_FILENAME VARCHAR2(100), 
	RENAMED_FILENAME VARCHAR2(100), 
	READCOUNT NUMBER DEFAULT 0, 
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    CREATE_DATE DATE DEFAULT SYSDATE, 
    MODIFY_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT PK_BOARD_NO PRIMARY KEY(NO),
    CONSTRAINT FK_WRITER FOREIGN KEY(WRITER_ID) REFERENCES MEMBER(ID) ON DELETE SET NULL
);

COMMENT ON COLUMN BOARD.NO IS '게시글번호';
COMMENT ON COLUMN BOARD.WRITER_ID IS '게시글작성자';
COMMENT ON COLUMN BOARD.TITLE IS '게시글제목';
COMMENT ON COLUMN BOARD.CONTENT IS '게시글내용';
COMMENT ON COLUMN BOARD.TYPE IS '게시글 타입';
COMMENT ON COLUMN BOARD.ORIGINAL_FILENAME IS '첨부파일원래이름';
COMMENT ON COLUMN BOARD.RENAMED_FILENAME IS '첨부파일변경이름';
COMMENT ON COLUMN BOARD.READCOUNT IS '조회수';
COMMENT ON COLUMN BOARD.STATUS IS '상태값(Y/N)';
COMMENT ON COLUMN BOARD.CREATE_DATE IS '게시글올린날짜';
COMMENT ON COLUMN BOARD.MODIFY_DATE IS '게시글수정날짜';

DROP SEQUENCE SEQ_BOARD_NO;
CREATE SEQUENCE SEQ_BOARD_NO;


DESC BOARD;

INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL, 'admin', '게시글 1',  '게시글 테스트 입니다.', 'B1', '원본파일명.txt', '변경된파일명.txt', DEFAULT, 'Y', SYSDATE, SYSDATE);

BEGIN
    FOR N IN 1..52
    LOOP
        INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL, 'admin', '게시글 '||SEQ_BOARD_NO.CURRVAL , '게시글 테스트입니다.'||SEQ_BOARD_NO.CURRVAL, 'B'||SEQ_BOARD_NO.CURRVAL, null, null, DEFAULT, 'Y', SYSDATE, SYSDATE);
    END LOOP;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/


COMMIT;
SELECT * FROM BOARD;

--------------------------------------------------------------------
------------------------- REPLY 관련 테이블 -------------------------
--------------------------------------------------------------------

DROP TABLE REPLY CASCADE CONSTRAINTS;

CREATE TABLE REPLY(
  NO NUMBER PRIMARY KEY,
  BOARD_NO NUMBER,
  WRITER_ID VARCHAR2(200),
  CONTENT VARCHAR2(400),
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
  CREATE_DATE DATE DEFAULT SYSDATE,
  MODIFY_DATE DATE DEFAULT SYSDATE,
  FOREIGN KEY (BOARD_NO) REFERENCES BOARD,
  FOREIGN KEY (WRITER_ID) REFERENCES MEMBER
);

DROP SEQUENCE SEQ_REPLY_NO;
CREATE SEQUENCE SEQ_REPLY_NO;

COMMENT ON COLUMN "REPLY"."NO" IS '댓글번호';
COMMENT ON COLUMN "REPLY"."BOARD_NO" IS '댓글이작성된게시글';
COMMENT ON COLUMN "REPLY"."WRITER_ID" IS '댓글작성자';
COMMENT ON COLUMN "REPLY"."CONTENT" IS '댓글내용';
COMMENT ON COLUMN "REPLY"."STATUS" IS '상태값(Y/N)';
COMMENT ON COLUMN "REPLY"."CREATE_DATE" IS '댓글올린날짜';
COMMENT ON COLUMN "REPLY"."MODIFY_DATE" IS '댓글수정날짜';



INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, 51, 'admin', '안녕하세요.', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, 50, 'admin', '반갑습니다.', DEFAULT, DEFAULT, DEFAULT);

BEGIN
    FOR N IN 1..52
    LOOP
        INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, N, 'admin', '안녕하세요.', DEFAULT, DEFAULT, DEFAULT);
        INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, N, 'admin', '안녕하세요.', DEFAULT, DEFAULT, DEFAULT);
        INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, N, 'admin', '안녕하세요.', DEFAULT, DEFAULT, DEFAULT);
    END LOOP;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/

COMMIT;

SELECT * FROM REPLY;



--------------------------------DDL 끝-------------------------------------------

-------------------------------Ground Table------------------------------
-------------------------------------------------------------------------
DROP TABLE GROUND CASCADE CONSTRAINTS;
CREATE TABLE GROUND (
    G_NO VARCHAR2(100) PRIMARY KEY,
    G_SVCNM VARCHAR2(500), 
    G_PLACENM VARCHAR2(50),
    G_AREANM VARCHAR2(50),
    G_URL VARCHAR2(1000),
    G_IMGURL VARCHAR2(1000),
    G_PLACE_X VARCHAR2(100),
    G_PLACE_Y VARCHAR2(100),
    G_PAY VARCHAR2(50),
    G_TEL VARCHAR2(100),
    G_START VARCHAR2(100),
    G_END VARCHAR2(100)
);

DROP SEQUENCE SEQ_GROUND_NO;
CREATE SEQUENCE SEQ_GROUND_NO;

INSERT INTO GROUND (
    G_NO,
    G_SVCNM,
    G_PLACENM,
    G_AREANM,
    G_URL,
    G_IMGURL,
    G_PLACE_X,
    G_PLACE_Y,
    G_PAY,
    G_TEL,
    G_START,
    G_END
) VALUES (
'S220112143538849507',
'풋살 / 방배 / 22년 3월 1~31일 / 평일 07:00~18:00 (선착순)',
'방배배수지체육공원',
'서초구',
'https://yeyak.seoul.go.kr/web/reservation/selectReservView.do?rsv_svc_id=S220223155039287833',
'https://yeyak.seoul.go.kr/web/common/file/FileDown.do?file_id=1645599093165CN8N29HRU3MHA532A8SLBKJTQ',
'126.9924890287',
'37.4730044433',
'유료',
'02-2155-6211',
'07:00',
'15:00'
);

COMMIT;

SELECT * FROM GROUND;

SELECT G_NO,
       G_SVCNM,
       G_PLACENM,
       G_AREANM,
       G_URL,
       G_IMGURL,
       G_PLACE_X,
       G_PLACE_Y,
       G_PAY,
       G_TEL,
       G_START,
       G_END
FROM GROUND order BY G_NO DESC;

-------------------------------Ground Table------------------------------
-------------------------------------------------------------------------

